spring:
  application:
    name: ms-users
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/DiLisa-Matias
      client:
        provider:
          keycloak:
            token-uri:  http://localhost:8080/realms/DiLisa-Matias/protocol/openid-connect/token
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: api-gateway
            client-secret: CUzx94kxE4xKmPw3obXC9nr0MbI95XNW
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8091

keycloakParams:
  keycloak:
    serverUrl: http://localhost:8080/
    realm: DiLisa-Matias
    clientId: ms-client
    clientSecret: cubAo9EOG4aVvm6uTYSkLUgA00Uecdnk